// actions


export const FETCH_POSTLIST_DATA = 'FETCH_POSTLIST_DATA';
export const FETCH_POSTLIST_DATA_START = 'FETCH_POSTLIST_DATA_START';
export const FETCH_POSTLIST_DATA_SUCCESS = 'FETCH_POSTLIST_DATA_SUCCESS';
export const FETCH_POSTLIST_DATA_FAILED = 'FETCH_POSTLIST_DATA_FAILED';
export const FETCH_POSTLIST_DATA_RESET = 'FETCH_POSTLIST_DATA_RESET';


export const FETCH_POSTTYPELIST_DATA = 'FETCH_POSTTYPELIST_DATA';
export const FETCH_POSTTYPELIST_DATA_START = 'FETCH_POSTTYPELIST_DATA_START';
export const FETCH_POSTTYPELIST_DATA_SUCCESS = 'FETCH_POSTTYPELIST_DATA_SUCCESS';
export const FETCH_POSTTYPELIST_DATA_FAILED = 'FETCH_POSTTYPELIST_DATA_FAILED';
export const FETCH_POSTTYPELIST_DATA_RESET = 'FETCH_POSTTYPELIST_DATA_RESET';

export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const FETCH_POST_DETAIL_START = 'FETCH_POST_DETAIL_START';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';
export const FETCH_POST_DETAIL_FAILED = 'FETCH_POST_DETAIL_FAILED';
export const CLEAR_POST_DETAIL = 'CLEAR_POST_DETAIL';


export const FETCH_POSTDETAIL_DATA = 'FETCH_POSTDETAIL_DATA';
export const FETCH_POSTDETAIL_DATA_START = 'FETCH_POSTDETAIL_DATA_START';
export const FETCH_POSTDETAIL_DATA_SUCCESS = 'FETCH_POSTDETAIL_DATA_SUCCESS';
export const FETCH_POSTDETAIL_DATA_FAILED = 'FETCH_POSTDETAIL_DATA_FAILED';
export const FETCH_POSTDETAIL_DATA_RESET = 'FETCH_POSTDETAIL_DATA_RESET';

export const FETCH_PAGE_DETAIL = 'FETCH_PAGE_DETAIL';
export const FETCH_PAGE_DETAIL_START = 'FETCH_PAGE_DETAIL_START';
export const FETCH_PAGE_DETAIL_SUCCESS = 'FETCH_PAGE_DETAIL_SUCCESS';
export const FETCH_PAGE_DETAIL_FAILED = 'FETCH_PAGE_DETAIL_FAILED';
export const CLEAR_PAGE_DETAIL = 'CLEAR_PAGE_DETAIL';


export const FETCH_PDP_DATA = 'FETCH_PDP_DATA';
export const FETCH_PDP_DATA_START = 'FETCH_PDP_DATA_START';
export const FETCH_PDP_DATA_SUCCESS = 'FETCH_PDP_DATA_SUCCESS';
export const FETCH_PDP_DATA_FAILED = 'FETCH_PDP_DATA_FAILED';
export const RESET_PDP_DATA = 'RESET_PDP_DATA';

// Userlist actions
export const FETCH_USRLIST_DATA = 'FETCH_USRLIST_DATA';
export const FETCH_USRLIST_DATA_START = 'FETCH_USRLIST_DATA_START';
export const FETCH_USRLIST_DATA_SUCCESS = 'FETCH_USRLIST_DATA_SUCCESS';
export const FETCH_USRLIST_DATA_FAILED = 'FETCH_USRLIST_DATA_FAILED';
export const FETCH_USRLIST_DATA_RESET = 'FETCH_USRLIST_DATA_RESET';
